// Wisdom by Bapoo - old-school proverbs, English only (no non-English script).
// Each category blends well-known traditional proverbs (translated to English)
// with newly written sayings composed in that same folk-wisdom voice, to give
// a large, varied set without repeating a handful of quotes.

(function () {
  var HINDI = [
    "A drop of water makes an ocean.",
    "As you sow, so shall you reap.",
    "You cannot clap with one hand.",
    "Where there is unity, there is strength.",
    "Speak the truth, but speak it sweetly.",
    "Slow and steady wins the race.",
    "A rolling stone gathers no moss.",
    "The one who digs a pit for others falls into it himself.",
    "Empty vessels make the most noise.",
    "Necessity is the mother of invention.",
    "A guest is to be treated like a king.",
    "Don't judge a book by its cover.",
    "The tree that bends survives the storm.",
    "Even a small lamp can light a large room.",
    "A tree is known by its fruit.",
    "Patience bears sweet fruit.",
    "He who has courage never feels alone.",
    "Where there is a will, there is a way.",
    "Do not count your chickens before they hatch.",
    "A friend in need is a friend indeed.",
    "The elephant's mouth stays open even in sleep.",
    "Bad company spoils good character.",
    "One and one, if united, make eleven.",
    "The sky is not too high for those who try.",
    "Better a diamond with a flaw than a pebble without one.",
    "A river cuts through rock not because of its power, but its persistence.",
    "Even the ocean is made of small drops.",
    "The needle that mends should not be too sharp itself.",
    "Wisdom does not come with age alone, but with experience.",
    "The wound of a word is deeper than the wound of a sword.",
    "A wise enemy is better than a foolish friend.",
    "Every sixty years the season turns; hard times do not last forever.",
    "The dog barks, the caravan moves on.",
    "A single hand cannot cover the sun.",
    "One who plants a tree does not sit in its shade.",
    "What is written on the forehead cannot be erased by worry.",
    "Trust in effort as much as you trust in fate.",
    "Sweet words open doors that force cannot.",
    "The pot that boils quietest often holds the most.",
    "Honor a teacher as you honor a parent.",
    "The lamp does not shine on its own base, yet it lights every corner of the room.",
    "A borrowed shawl never keeps you as warm as your own.",
    "Even a king needs a farmer's field.",
    "The crow that struts like a peacock only tires itself out.",
    "A house built on kindness never falls in a storm.",
    "The river that forgets its source soon forgets its way.",
    "One ripe mango can sweeten the memory of a whole season.",
    "The strongest rope is woven from many thin threads.",
    "A closed fist holds nothing; an open hand receives everything.",
    "The mountain does not boast of its height; the traveler tells of it.",
    "Even the moon has its dark side, and still we call it beautiful.",
    "Sharpen your mind the way you sharpen a blade — slowly, and with care.",
    "A well full of water does not need to announce itself.",
    "The bird that arrives early does not always find the best branch, but it finds a branch.",
    "Kindness spoken once is remembered longer than gold given twice.",
    "The road feels shorter when it is walked with a friend.",
    "A cracked bell can still ring true.",
    "What the eyes cannot see, the heart often already knows.",
    "The banyan tree grows slowly, but its shade outlives the planter."
  ];

  var JEWISH = [
    "Man plans, and God laughs.",
    "Whoever saves a single life saves an entire world.",
    "The whole world is a narrow bridge; the important thing is not to be afraid.",
    "If you bend, bend all the way.",
    "Better a good enemy than a bad friend.",
    "A word is worth one coin; silence is worth two.",
    "God gave burdens, and also gave shoulders.",
    "When you have money in your pocket, you are wise, handsome, and you sing well too.",
    "Do not do unto others what is hateful to you.",
    "A half-truth is a whole lie.",
    "The doctor owes the patient nothing but the truth.",
    "If not now, when?",
    "Turn it over and over, for everything is in it.",
    "The best cure for the body is a quiet mind.",
    "Who is wise? One who learns from every person.",
    "Who is rich? One who is content with what they have.",
    "Who is strong? One who controls their own passions.",
    "In a place where there is no one acting with humanity, strive to be that person.",
    "Say little and do much.",
    "The world stands on three things: truth, justice, and peace.",
    "A guest should not be watched by his host, but the host by his guest.",
    "Give every person the benefit of the doubt.",
    "Worry does not empty tomorrow of its sorrow; it empties today of its strength.",
    "Better one hour of good deeds than a lifetime spent in the world to come.",
    "Whoever destroys one life, it is as if he destroyed an entire world.",
    "Do not separate yourself from the community.",
    "You are not obligated to complete the work, but neither are you free to abandon it.",
    "A candle loses nothing by lighting another candle.",
    "Even a thin thread strung together many times becomes a rope that can pull a lion.",
    "The wound heals, but the scar remains as a lesson.",
    "One who teaches a child is as though they built a whole world.",
    "Silence is a fence around wisdom.",
    "A little light dispels a lot of darkness.",
    "Do not look at the vessel, but at what is inside it.",
    "There is no leader like the one who has been a servant.",
    "He who chases after honor, honor flees from him.",
    "More than the calf wants to nurse, the cow wants to nurse it.",
    "Everything is foreseen, yet freedom of choice is given.",
    "A poor man is considered as good as dead.",
    "One mitzvah brings another mitzvah in its wake.",
    "Repent one day before your death — since no one knows the day, live every day well.",
    "Trouble shared is trouble halved.",
    "The dust of the earth was gathered from every corner, so that no one could say the earth belonged more to one place than another.",
    "A generous eye, a humble spirit, and a modest soul are the marks of a good person.",
    "As the fig tree is watched over until its fruit ripens, so are the words of the Torah meditated upon until they are understood.",
    "If I am not for myself, who will be for me? And if I am only for myself, what am I?",
    "The longest road is the one that leads back home.",
    "Better to be a tail among lions than a head among foxes.",
    "A person is led down the path they choose to walk.",
    "The wise see with their ears; fools listen with their eyes.",
    "Charity given quietly weighs more than charity given loudly.",
    "One who saves a coin has, in time, saved a fortune.",
    "The wise man hears one word and understands two.",
    "A blessing rests only on what is hidden from the eye — and on a table that has known hunger.",
    "The wound you cannot see is the one that takes longest to heal.",
    "Learn as if you will live forever; live as if you will die tomorrow.",
    "No wine bought at auction has a discount, and no wisdom worth having comes cheap.",
    "Better a bird in your hand than a bird you only wished for.",
    "Every generation must see itself as though it left Egypt anew."
  ];

  var POLISH = [
    "Not my circus, not my monkeys.",
    "A guest in the house is God in the house.",
    "Better to lose with a wise man than to win with a fool.",
    "A bird is known by its song, a man by his speech.",
    "Old friends and old wine are best.",
    "Don't teach your father how to make children.",
    "What Monday starts, the whole week follows.",
    "As you make your bed, so you must lie in it.",
    "A guest is like a fish — after three days, it stinks.",
    "Without work there are no cookies.",
    "The apple does not fall far from the tree.",
    "Fortune favors the brave.",
    "Grasp all, lose all.",
    "Every road leads home eventually.",
    "A drowning man will grasp at a razor.",
    "There's no bad without some good.",
    "One should measure the coat according to the cloth.",
    "Everyone praises their own goose.",
    "A promise is a promise, even if it's whispered to the wind.",
    "The devil is not as terrible as he is painted.",
    "Better a sparrow in hand than a pigeon on the roof.",
    "The mother knows best who was fed with her own milk.",
    "What you spare in youth, you spend in old age.",
    "As the old bird sings, so the young one learns.",
    "Even a small fire can burn down a great forest.",
    "Do not swap a bird already in your hand for one still flying.",
    "The wolf changes his coat, not his habits.",
    "A silent guest sees more than a loud one.",
    "Give the calf where it is expected, and the cow will grow horns for you in return.",
    "A closed mouth catches no flies.",
    "One does not build a bridge from the middle.",
    "It's easier to break than to build.",
    "The healthy do not understand the sick, nor the full the hungry.",
    "A hundred friends is better than a hundred rubles.",
    "The pot calls the kettle black, and both are equally sooty.",
    "Even a stopped clock is right twice a day.",
    "He who digs a pit for another falls into it himself.",
    "A good neighbor is worth more than a distant cousin.",
    "The wagon should be greased so it does not creak.",
    "What the peasant does not know, he will not eat.",
    "A guest's first day is gold, the second is silver, the third is lead.",
    "It is not the cowl that makes the monk.",
    "Every path has its own puddle.",
    "A word once spoken cannot be caught again, like a bird once flown.",
    "Small pot, but it boils quickly.",
    "The forest hears, the field sees.",
    "One swallow does not make a spring.",
    "A candle burns brightest just before it gutters out — do not wait for the end to shine.",
    "A field left fallow still remembers how to grow.",
    "Snow covers many sins, but the thaw reveals them all.",
    "The axe that is kept sharp is the one that is used often.",
    "A house is not built by wishing, but by carrying one stone at a time.",
    "The cart that creaks the loudest is not always the one that breaks first.",
    "Bread shared at a small table tastes better than a feast eaten alone.",
    "A stork does not return to a nest that was never mended.",
    "The frost that comes early teaches the harvest to hurry.",
    "A quiet river still carves the deepest bed.",
    "Wisdom kept in the cellar is no warmer than the winter outside.",
    "The old oak bends in the storm so the young sapling does not have to."
  ];

  var CATEGORIES = [
    { id: "hindi", label: "Hindi", icon: "🪔" },
    { id: "jewish", label: "Jewish", icon: "✡️" },
    { id: "polish", label: "Polish", icon: "🦅" },
    { id: "random", label: "Random", icon: "🎲" }
  ];

  window.WISDOM_DATA = { hindi: HINDI, jewish: JEWISH, polish: POLISH };
  window.WISDOM_CATEGORIES = CATEGORIES;
})();
