// Wisdom by Bapoo - old-school proverbs, each shown with its original-language
// phrase spelled out phonetically in English letters (no non-English script)
// on top and the English translation below. Only well-known, verifiable
// traditional proverbs are included so the transliterations are authentic.

(function () {
  var HINDI = [
    { native: "Boond boond se sagar banta hai", english: "A drop of water makes an ocean." },
    { native: "Jaisi karni waisi bharni", english: "As you sow, so shall you reap." },
    { native: "Ek haath se taali nahi bajti", english: "You cannot clap with one hand." },
    { native: "Ekta mein bal hai", english: "Where there is unity, there is strength." },
    { native: "Sach boliye, meetha boliye", english: "Speak the truth, but speak it sweetly." },
    { native: "Dheeraj ke phal meethe hote hain", english: "Patience bears sweet fruit." },
    { native: "Jo khode gaddha doosron ke liye, khud hi usmein girta hai", english: "He who digs a pit for others falls into it himself." },
    { native: "Khaali bartan zyada awaaz karte hain", english: "Empty vessels make the most noise." },
    { native: "Zaroorat aavishkar ki janani hai", english: "Necessity is the mother of invention." },
    { native: "Atithi Devo Bhava", english: "A guest is to be treated like a god." },
    { native: "Doobte ko tinke ka sahara", english: "A drowning man will clutch at a straw." },
    { native: "Sau sunaar ki, ek luhaar ki", english: "A hundred taps from a goldsmith equal one blow from a blacksmith." },
    { native: "Nach na jaane aangan tedha", english: "One who can't dance blames the crooked courtyard." },
    { native: "Andhon mein kaana raja", english: "In the land of the blind, the one-eyed man is king." },
    { native: "Ghar ki murgi daal barabar", english: "The chicken at home is worth no more than lentils." },
    { native: "Doodh ka jala chhaachh bhi phoonk phoonk kar peeta hai", english: "Once burned by milk, a person blows even on buttermilk." },
    { native: "Jitni chadar ho utne hi pair phailaye", english: "Stretch your legs only as far as your blanket reaches." },
    { native: "Jaan hai to jahaan hai", english: "Where there is life, there is the world." },
    { native: "Neem hakim khatra-e-jaan", english: "A half-baked physician is a danger to life." },
    { native: "Bandar kya jaane adrak ka swaad", english: "What does a monkey know of the taste of ginger?" },
    { native: "Jaisi sangat waisi rangat", english: "You take on the color of the company you keep." },
    { native: "Jab jaago tabhi savera", english: "Whenever you wake up, that is your morning." },
    { native: "Hathi ke daant khane ke aur, dikhane ke aur", english: "An elephant has one set of teeth for eating and another for show." },
    { native: "Aam ke aam, guthliyon ke daam", english: "Get the mangoes, and sell the seeds too." },
    { native: "Chaar din ki chandni, phir andheri raat", english: "Four days of moonlight, then a dark night." },
    { native: "Jiski lathi uski bhains", english: "Whoever holds the stick owns the buffalo." },
    { native: "Door ke dhol suhaavane", english: "Drums sound sweeter from a distance." },
    { native: "Ab pachtaye hot kya jab chidiya chug gayi khet", english: "What use is regret once the birds have already eaten the field? (No use crying over spilt milk.)" },
    { native: "Nau sau chuhe khakar billi haj ko chali", english: "After eating nine hundred mice, the cat went on a pilgrimage." },
    { native: "Na rahega baans, na bajegi bansuri", english: "If there is no bamboo, there will be no flute." },
    { native: "Ek anar sau bimar", english: "One pomegranate, and a hundred sick people wanting it." },
    { native: "Oont ke muh mein jeera", english: "A cumin seed in a camel's mouth." },
    { native: "Na nau man tel hoga na Radha nachegi", english: "There will be no nine maunds of oil, and no dance either." },
    { native: "Ghar ka bhedi Lanka dhaye", english: "An insider from home is the one who brings down Lanka." },
    { native: "Aage kuan peeche khai", english: "A well ahead, a ditch behind." },
    { native: "Andha baante revdi, phir phir apno ko de", english: "A blind man handing out sweets keeps giving to his own people." },
    { native: "Saanp bhi mar jaye aur laathi bhi na tootay", english: "Kill the snake without breaking the stick." },
    { native: "Dhobi ka kutta na ghar ka na ghat ka", english: "The washerman's dog belongs neither to the house nor the riverbank." },
    { native: "Billi ke gale mein ghanti kaun baandhe", english: "Who will bell the cat?" },
    { native: "Ek pantha do kaaj", english: "Two tasks done on a single path." },
    { native: "Neki kar dariya mein daal", english: "Do a good deed, and cast it into the river." },
    { native: "Ulta chor kotwal ko daante", english: "The thief scolds the police officer." },
    { native: "Haath kangan ko aarsi kya", english: "What need is there for a mirror to see the bangle on your own hand?" },
    { native: "Jangal mein mor naacha kisne dekha", english: "If a peacock dances in the forest, who is there to see it?" },
    { native: "Jal mein rehkar magar se bair theek nahin", english: "It is not wise to make an enemy of the crocodile while living in its water." },
    { native: "Jaati na poochho sadhu ki", english: "Do not ask a holy man his caste." },
    { native: "Ishq andha hota hai", english: "Love is blind." },
    { native: "Utaavla so baavla", english: "The hasty one is the foolish one." },
    { native: "Ek hi saanche mein dhale hain", english: "Cast from the very same mold." },
    { native: "Ek parhez lakh dawa", english: "One ounce of prevention is worth a hundred thousand medicines." },
    { native: "Os chaatne se pyaas nahi bujhti", english: "Licking the morning dew never quenched anyone's thirst." },
    { native: "Kaali maa ke gore bachche", english: "A black hen can still lay a white egg." },
    { native: "Kaam kaam ko sikhaata hai", english: "Work itself is what teaches the worker." },
    { native: "Kuch na hone se thoda accha hai", english: "A little is better than nothing at all." },
    { native: "Kumhaar apne bartan sarahta hai", english: "Every potter praises his own pots." },
    { native: "Kutte ki poonchh tedhi hi hoti hai", english: "A dog's tail stays crooked no matter what." },
    { native: "Koode ke bhi din phirte hain", english: "Even a heap of rubbish has its lucky day." },
    { native: "Jiska ilaaj nahi uska koi upaay nahi", english: "What cannot be cured must simply be endured." },
    { native: "Jaisa raja waisi praja", english: "As is the king, so are his subjects." },
    { native: "Jhoothe ki yaddasht tez honi chahiye", english: "A liar had better have a sharp memory." },
    { native: "Duvidha mein dono gaye, maya mili na Ram", english: "Torn between two paths, he lost both - neither wealth nor God." },
    { native: "Deewa tale andhera", english: "It is always darkest directly beneath the lamp." },
    { native: "Khari mazoori chokha kaam", english: "Fair wages make for fine work." },
    { native: "Kheti khasam seti", english: "A field flourishes best under its own owner's eye." },
    { native: "Gadhe ko angoor baagh se kya matlab", english: "What use does a donkey have for a vineyard?" },
    { native: "Gud khaaye, gulgulon se parhez", english: "He eats the jaggery but turns up his nose at the sweets." },
    { native: "Gehun ke saath ghun bhi pista hai", english: "When the wheat is ground, the chaff is ground along with it." },
    { native: "Ghayal ki gati ghayal hi jaane", english: "Only the wounded truly know the pain of the wound." },
    { native: "Chaube gaye chhabbe banne, dubbe hoke aaye", english: "He set out to rise from priest to something grander, and came home demoted instead." },
    { native: "Jahan phool wahan kaante", english: "Where there are flowers, there are thorns too." },
    { native: "Hatheli par sarson nahi jamti", english: "Mustard seed does not sprout on the palm of your hand." },
    { native: "Jaan bachi lakhon paaye", english: "A life saved is worth a fortune gained." },
    { native: "Apne muh miyan mithu", english: "Calling yourself sweet by your own mouth means nothing." },
    { native: "Paanchon ungliyan barabar nahi hoti", english: "Not even the five fingers of one hand are equal." },
    { native: "Jahan chah wahan raah", english: "Where there is a will, there is a way." },
    { native: "Der aaye durust aaye", english: "Better late than never." },
    { native: "Ant bhala to sab bhala", english: "All is well that ends well." },
    { native: "Chor-chor mausere bhai", english: "Thieves are all cousins to one another." },
    { native: "Munh mein Ram, bagal mein churi", english: "Ram's name on the lips, a knife tucked under the arm." },
    { native: "Unchi dukan phika pakwan", english: "A tall shop, but bland food inside." },
    { native: "Apna hath jagannath", english: "Your own hand is your lord." },
    { native: "Daal mein kala", english: "There's something black in the lentils." },
    { native: "Jo garajte hain vo barsate nahin", english: "Those who thunder the loudest rarely bring the rain." },
    { native: "Naam liya aur shaitaan hazir", english: "Speak of the devil, and he appears." },
    { native: "Sanch ko aanch kya", english: "Truth has nothing to fear from fire." },
    { native: "Jaisa desh, vaisa bhes", english: "Dress as the country does." },
    { native: "Boye ped babul ka to aam kahan se paaye", english: "Plant a thornbush, and where will you find mangoes?" },
    { native: "Jananee janmabhoomischa swargaadapi gareeyasi", english: "One's mother and one's homeland outweigh even heaven." },
    { native: "Aasman se gira, khajoor mein atka", english: "Fell from the sky, and got stuck in a date palm." }
  ];

  var JEWISH = [
    { native: "Eizehu chacham? Halomed mikol adam.", english: "Who is wise? One who learns from every person." },
    { native: "Eizehu ashir? Hasameach b'chelko.", english: "Who is rich? One who is happy with what he has." },
    { native: "Eizehu gibor? Hakovesh et yitzro.", english: "Who is mighty? One who conquers his own impulses." },
    { native: "Im lo achshav, eimatai?", english: "If not now, when?" },
    { native: "Im ein ani li, mi li? U'ch'she'ani le'atzmi, mah ani?", english: "If I am not for myself, who will be for me? And if I am only for myself, what am I?" },
    { native: "Lo alecha hamlacha ligmor, v'lo atah ben chorin l'hibatel mimena", english: "You are not obligated to complete the work, but neither are you free to abandon it." },
    { native: "Kol hamekayem nefesh achat, ke'ilu kiyem olam malei", english: "Whoever saves one life, it is as if he saved an entire world." },
    { native: "Kol Yisrael arevim zeh ba'zeh", english: "All people are responsible for one another." },
    { native: "Marbeh tzedakah, marbeh shalom", english: "The more charity given, the more peace in the world." },
    { native: "Tzedakah tatzil mimavet", english: "Charity saves from death." },
    { native: "Eizehu mechubad? Hamechabed et habriyot.", english: "Who is honored? One who honors others." },
    { native: "Hevu metunim baddin", english: "Be deliberate in judgment." },
    { native: "Yehi veitecha beit va'ad lachachamim", english: "Let your home be a meeting place for the wise." },
    { native: "Aseh lecha rav, ukeneh lecha chaver", english: "Appoint for yourself a teacher, and acquire for yourself a friend." },
    { native: "Harchek mishachen ra", english: "Keep far from a bad neighbor." },
    { native: "Ehov et hammelachah, usena et harabbanut", english: "Love work, and despise holding high office." },
    { native: "Ein bor yerei chet", english: "One who has not studied cannot truly fear sin." },
    { native: "Al tihyu cha'avadim hamshammeshin et harav al menat lekabbel peras", english: "Do not serve merely to receive a reward." },
    { native: "Histakkel bishloshah devarim", english: "Reflect on three things: where you came from, where you are going, and before whom you will one day account." },
    { native: "Yehi chevod chaverach chaviv aleicha", english: "Let your friend's honor be as dear to you as your own." },
    { native: "Velo hammidrash hu ha'ikkar, ella hamma'aseh", english: "Study is not the main thing - action is." },
    { native: "Chayav adam lomar bishvili nivra ha'olam", english: "Every person must say: the world was created for my sake." },
    { native: "Al tifrosh min hatzibur", english: "Do not separate yourself from the community." },
    { native: "Shtika k'hoda'ah damia", english: "Silence is as good as agreement." },
    { native: "Tafasta merube, lo tafasta", english: "If you grasp for too much, you end up grasping nothing." },
    { native: "Kol haposel, bemumo posel", english: "Whoever finds fault in others reveals his own flaw." }
  ];

  var YIDDISH = [
    { native: "Der mentsh trakht, un Got lakht", english: "Man plans, and God laughs." },
    { native: "A halber emes iz a gantse lign", english: "A half-truth is a whole lie." },
    { native: "Az me ken nisht ariber, geyt men arunter", english: "If you can't go over it, go under it." },
    { native: "Mit gelt in kesheneh, bistu klug, bistu sheyn, un ken oykh gut zingen", english: "With money in your pocket, you are wise, you are handsome, and you sing well too." },
    { native: "Beser a gutn soyne eyder a shlekhtn fraynd", english: "Better a good enemy than a bad friend." },
    { native: "Az got vil, shist a bezem oykh", english: "When God wills it, even a broom can shoot." },
    { native: "Shlof gikher, me darf dos kishn", english: "Sleep faster, we need the pillow." },
    { native: "Az men est khazir, zol es rinen fun bord", english: "If you're going to eat pork, let it drip from your beard." },
    { native: "Az di kats volt gehat fligl, volt zi ale feygl oyfgegesn", english: "If the cat had wings, it would eat all the birds." },
    { native: "Me ken nisht tantsn oyf tsvey khasenes mit eyn hintn", english: "You can't dance at two weddings with one rear end." },
    { native: "Az men hot nisht keyn seykhl, hot men fis", english: "If you don't have brains, you'd better have legs." },
    { native: "Kleyne kinder, kleyne freydn; groyse kinder, groyse leydn", english: "Small children, small joys; big children, big troubles." },
    { native: "Az men muz, ken men", english: "When one must, one can." },
    { native: "Az Got vil shtrofn a mentshn, nemt er im op dem seykhl", english: "When God wants to punish someone, He first takes away their common sense." },
    { native: "Alle kales zenen sheyn; alle meysim zenen frum", english: "All brides are beautiful; all the dead are pious." },
    { native: "Gelt geyt tsu gelt", english: "Money goes to money." },
    { native: "Az me lebt, derlebt men", english: "If you live long enough, you live to see everything." },
    { native: "Der oylem iz a goylem", english: "The public is a golem (a mindless mass)." },
    { native: "Keyner zet nit zayn eygenem hoyker", english: "No one sees the hump on his own back." },
    { native: "Keyner veys nit vemen der shukh kvetsht, nor der vos geyt in im", english: "No one knows whose shoe pinches, except the one who wears it." },
    { native: "Yeder mentsh hot zikh zayn pekl", english: "Every person carries his own bundle of troubles." },
    { native: "Tsores zaynen far dem mentshn vi zhaver far ayzn", english: "Troubles are to a person what rust is to iron." },
    { native: "In a sheynem epl gefint men a mol a vorem", english: "Even in a beautiful apple you sometimes find a worm." },
    { native: "Beser a patsh fun a khokhem eyder a kush fun a nar", english: "Better a slap from a wise man than a kiss from a fool." },
    { native: "Bay ferd kukt men af di tseyn; bay a mentshn afn seykhl", english: "With a horse you check the teeth; with a person you check the mind." },
    { native: "Der tayvl iz nit azoy shvarts vi men molt im", english: "The devil is not as black as he is painted." },
    { native: "Bay nakht zenen ale ki shvarts", english: "At night, all cows look black." },
    { native: "A shvartse hun ken oykh leygn a vays ey", english: "A black hen can lay a white egg too." },
    { native: "Fun leydike feser iz der lyarem greser", english: "Empty barrels make the loudest noise." },
    { native: "Eyn alter fraynd iz beser vi naye tsvey", english: "One old friend is worth more than two new ones." },
    { native: "Eyn guter fraynd iz beser fun tsen kroyvim", english: "One good friend is worth more than ten relatives." },
    { native: "Itlekhs tepl gefint zikh zayn dekl", english: "Every pot finds its own lid." },
    { native: "Libe makht blind", english: "Love makes you blind." },
    { native: "Nito keyn royz on derner", english: "There is no rose without thorns." },
    { native: "Mit honik ken men khapn mer flign vi mit esik", english: "You catch more flies with honey than with vinegar." },
    { native: "Gey pavolye, vestu gikher kumen", english: "Go slowly, and you'll get there faster." },
    { native: "Eyn oyg hot mer gloybn vi tsvey oyern", english: "One eye is worth more trust than two ears." },
    { native: "Der emes kumt aroys vi boyml afn vaser", english: "The truth always rises to the surface, like oil on water." },
    { native: "Vent hobn oyern", english: "Walls have ears." },
    { native: "Takhrikhim hobn nit keyn keshenes", english: "Shrouds have no pockets." },
    { native: "Ale shusters geyen borves", english: "All shoemakers go around barefoot." },
    { native: "Arbet iz keyn shand", english: "Work is no disgrace." },
    { native: "Shtil vaser grobt tif", english: "Still water digs deep." },
    { native: "Az dos harts iz ful, geyen di oygn iber", english: "When the heart is full, the eyes overflow." },
    { native: "A shlekhter sholem iz beser vi a guter krig", english: "A bad peace is better than a good war." },
    { native: "Di velt iz sheyn nor di mentshn makhn zi mies", english: "The world is beautiful, but people make it ugly." },
    { native: "On gelt iz keyn velt", english: "Without money, there's no world to speak of." },
    { native: "Der karger ligt af dem gelt vi a hunt afn beyn", english: "The miser guards his money like a dog guards its bone." },
    { native: "Got hot lib dem oreman un helft dem nogid", english: "God loves the poor man, yet helps the rich one." },
    { native: "Di zun shaynt glaykh af orem un raykh", english: "The sun shines the same on rich and poor alike." },
    { native: "Koved iz vi a shotn: vos mer men loyft im nokh, alts vayter antloyft er", english: "Honor is like a shadow: the more you chase it, the farther it runs." },
    { native: "Ver es grobt a grub far yenem falt aleyn arayn", english: "He who digs a pit for someone else falls into it himself." },
    { native: "A hunt vos bilt bayst nit", english: "A dog that barks doesn't bite." },
    { native: "Az men ken nit baysn zol men di tseyn nit vayzn", english: "If you can't bite, don't bare your teeth." },
    { native: "Ven di kats shloft, tantsn di mayz", english: "When the cat sleeps, the mice dance." },
    { native: "A ber lernt men oykh oys tantsn", english: "Even a bear can be taught to dance." },
    { native: "Di tsayt iz der bester dokter", english: "Time is the best doctor." },
    { native: "Di tsayt iz tayerer fun gelt", english: "Time is more precious than money." },
    { native: "Nito keyn eybike zakh af der velt", english: "Nothing in this world lasts forever." },
    { native: "A kluger farshteyt fun eyn vort tsvey", english: "A wise person hears one word and understands two." },
    { native: "Af eyn shlog falt keyn boym nit um", english: "A single blow does not fell a tree." },
    { native: "A barg mit a barg kumt zikh nit tsunoyf, ober a mentsh mit a mentshn yo", english: "Two mountains never meet, but two people do." },
    { native: "Dos epele falt nit vayt fun beymele", english: "The little apple never falls far from its little tree." },
    { native: "Verter zol men vegn un nit tseyln", english: "Words should be weighed, not merely counted." },
    { native: "Mit a lefl ken men dem yam nit oys'shepn", english: "You cannot empty the sea with a spoon." },
    { native: "Az ich vel zayn vi er, ver vet zayn vi ich", english: "If I try to be like him, who will be like me?" },
    { native: "Vos m'iz geveynt af der yugent, azoy tut men af der elter", english: "The habits formed in youth are what we follow in old age." },
    { native: "Az me ken nit vi me vil, muz men vellen vi me ken", english: "If you can't do as you wish, you must wish to do as you can." },
    { native: "Ehren is fil tei'erer far gelt", english: "Honor is worth far more than money." },
    { native: "Mit gelt ken men nit shtoltsiren, me ken es laycht farliren", english: "Don't boast of money - it's easily lost." },
    { native: "Far gelt bakumt men alts, nor keyn sechel nit", english: "Money buys everything except good sense." },
    { native: "Di kats hot lib fish, nor zi vil di fis nit ayn-netsn", english: "The cat loves fish, but won't wet her paws to catch it." },
    { native: "Kinder un gelt is a shaine velt", english: "Children and money make for a beautiful world." },
    { native: "Di liebe is zees, nor zi iz gut mit broyt", english: "Love is sweet, but it's better with bread." },
    { native: "Kleine kinder lozn nit shloffen, grosse kinder lozn nit leben", english: "Small children won't let you sleep, grown children won't let you live." },
    { native: "Me varft nit aroys di umreyne vasser eyder me hot reynes", english: "Don't throw out the dirty water until you have clean water to replace it." },
    { native: "A nar geyt tsvey mol dort vu a kliger geyt nit keyn eyntsik mol", english: "A fool goes twice where a wise man won't go even once." },
    { native: "Az der soyne falt, tor men zich nit freyen, ober me heybt im nit oyf", english: "When your enemy falls, don't celebrate - but don't help him up either." },
    { native: "Beser hern kloles eyder hern nebekh", english: "Better to be cursed than pitied." },
    { native: "Far a tsap hot men moyre fun fornt, far a ferd fun hintn, far a nar fun ale zaytn", english: "Be wary in front of a goat, behind a horse, and on every side of a fool." }
  ];

  var POLISH = [
    { native: "Gość w dom, Bóg w dom", english: "A guest in the house is God in the house." },
    { native: "Nie mój cyrk, nie moje małpy", english: "Not my circus, not my monkeys." },
    { native: "Jak sobie pościelesz, tak się wyśpisz", english: "As you make your bed, so shall you sleep in it." },
    { native: "Kto pod kim dołki kopie, sam w nie wpada", english: "He who digs a pit for others falls into it himself." },
    { native: "Lepiej późno niż wcale", english: "Better late than never." },
    { native: "Co ma wisieć, nie utonie", english: "What is meant to hang will not drown." },
    { native: "Gdzie kucharek sześć, tam nie ma co jeść", english: "Where there are six cooks, there is nothing to eat." },
    { native: "Nie chwal dnia przed zachodem słońca", english: "Don't praise the day before sunset." },
    { native: "Kto rano wstaje, temu Pan Bóg daje", english: "The early riser is rewarded." },
    { native: "Cudze chwalicie, swego nie znacie", english: "You praise what is foreign and do not know your own." },
    { native: "Prawdziwych przyjaciół poznaje się w biedzie", english: "True friends are recognized in hardship." },
    { native: "Nie ma tego złego, co by na dobre nie wyszło", english: "There is no bad that doesn't turn out good in the end." },
    { native: "Kropla drąży skałę", english: "A drop of water carves the rock." },
    { native: "Do trzech razy sztuka", english: "The third time is the charm." },
    { native: "Jak Kuba Bogu, tak Bóg Kubie", english: "As you treat God, so God treats you." },
    { native: "Gość jak ryba, po trzech dniach cuchnie", english: "A guest, like a fish, stinks after three days." },
    { native: "Bez pracy nie ma kołaczy", english: "Without work, there is no cake." },
    { native: "Kto pyta, nie błądzi", english: "He who asks does not go astray." },
    { native: "Ryba psuje się od głowy", english: "The fish rots from the head." },
    { native: "Mądry Polak po szkodzie", english: "A Pole is wise after the damage is done." },
    { native: "Nie wywołuj wilka z lasu", english: "Don't call the wolf out of the forest." },
    { native: "Darowanemu koniowi nie zagląda się w zęby", english: "Don't look a gift horse in the mouth." },
    { native: "Głodnemu chleb na myśli", english: "A hungry man's thoughts are on bread." },
    { native: "Kropla w morzu", english: "A drop in the ocean." },
    { native: "Lepszy wróbel w garści niż gołąb na dachu", english: "A sparrow in the hand is better than a pigeon on the roof." },
    { native: "Co kraj, to obyczaj", english: "Different country, different custom." },
    { native: "Do tanga trzeba dwojga", english: "It takes two to tango." },
    { native: "Dobry początek to połowa roboty", english: "A good beginning is half the work." },
    { native: "Dobrymi chęciami jest piekło wybrukowane", english: "The road to hell is paved with good intentions." },
    { native: "Gdy się człowiek spieszy, to się diabeł cieszy", english: "When a person hurries, the devil rejoices." },
    { native: "Historia się powtarza", english: "History repeats itself." },
    { native: "I uczony Homer drzemał czasem", english: "Even learned Homer dozed off now and then." },
    { native: "Jaki ojciec, taki syn", english: "Like father, like son." },
    { native: "Kto dwa zające goni, żadnego nie złapie", english: "He who chases two hares catches neither." },
    { native: "Kuj żelazo, póki gorące", english: "Strike the iron while it's hot." },
    { native: "Lepiej umrzeć stojąc niż żyć na kolanach", english: "Better to die standing than to live on your knees." },
    { native: "Nowa miotła dobrze zamiata", english: "A new broom sweeps clean." },
    { native: "Nie wszystko złoto, co się świeci", english: "Not all that glitters is gold." },
    { native: "Nie dziel skóry na niedźwiedziu", english: "Don't divide the bear's skin before you've caught the bear." },
    { native: "Pieniądze szczęścia nie dają", english: "Money doesn't buy happiness." },
    { native: "Punktualność jest grzecznością królów", english: "Punctuality is the courtesy of kings." },
    { native: "Śpiesz się powoli", english: "Make haste slowly." },
    { native: "Stara miłość nie rdzewieje", english: "Old love never rusts." },
    { native: "Szewc bez butów chodzi", english: "The shoemaker goes about in worn-out shoes." },
    { native: "Tonący brzytwy się chwyta", english: "A drowning man clutches at a razor." },
    { native: "Trafiła kosa na kamień", english: "The scythe struck the stone." },
    { native: "Tu leży pies pogrzebany", english: "That's where the dog lies buried." },
    { native: "Wchodząc między wrony, krakaj jak i one", english: "Among crows, caw as they do." },
    { native: "Więcej ludzi utonęło w kieliszku niż w morzu", english: "More people have drowned in a glass than in the sea." },
    { native: "Z deszczu pod rynnę", english: "Out of the rain and under the gutter spout." },
    { native: "Apetyt wzrasta w miarę jedzenia", english: "The appetite grows with the eating." },
    { native: "Zapomniał wół, jak cielęciem był", english: "The ox forgot that he was once a calf." },
    { native: "Daj mu palec, on za rękę chwyta", english: "Give him a finger, and he grabs your whole hand." },
    { native: "Stary do rady, a młody do zwady", english: "The old are for counsel, the young are for quarrels." },
    { native: "Całuj rękę, której ukąsić nie możesz", english: "Kiss the hand you cannot bite." },
    { native: "Wielkie ryby małe żrą", english: "Big fish devour little fish." },
    { native: "Pijaństwo jest dobrowolne szaleństwo", english: "Drunkenness is madness by choice." },
    { native: "Błędy lekarza pokrywa ziemia", english: "The doctor's mistakes are covered by the earth." },
    { native: "Jak się nie ma, co się lubi, to się lubi, co się ma", english: "If you don't have what you like, you learn to like what you have." },
    { native: "Nieszczęścia chodzą parami", english: "Misfortunes travel in pairs." },
    { native: "Niedaleko spada jabłko od jabłoni", english: "The apple doesn't fall far from the tree." },
    { native: "Co dwie głowy, to nie jedna", english: "Two heads are better than one." },
    { native: "Co nagle, to po diable", english: "What's done in haste is the devil's work." },
    { native: "Co za dużo, to niezdrowo", english: "Too much of anything isn't healthy." },
    { native: "Czym się strułeś, tym się lecz", english: "Cure yourself with what poisoned you." },
    { native: "Pies ogrodnika – sam nie zje i drugiemu nie da", english: "The gardener's dog - won't eat it himself, and won't let anyone else either." },
    { native: "Gdyby kózka nie skakała, to by nóżki nie złamała", english: "If the little goat hadn't jumped, it wouldn't have broken its leg." }
  ];

  var CATEGORIES = [
    { id: "hindi", label: "Hindi", icon: "🪔" },
    { id: "jewish", label: "Jewish", icon: "✡️" },
    { id: "yiddish", label: "Yiddish", icon: "🎻" },
    { id: "polish", label: "Polish", icon: "🦅" },
    { id: "random", label: "Random", icon: "🎲" },
    { id: "favorites", label: "Favorites", icon: "❤️" }
  ];

  window.WISDOM_DATA = { hindi: HINDI, jewish: JEWISH, yiddish: YIDDISH, polish: POLISH };
  window.WISDOM_CATEGORIES = CATEGORIES;
})();
